### ISSUE TITLE
Found the problem with the no sleep Forge version on servers!

### ISSUE THREAD

**Issue by Dunkmania101** [latedozer/Don-t-Sleep-Forges-#1]
In the Fabric version, you're setting the spawn point with "player.setSpawnPoint ", which works just fine. On the Forge version, you're getting the player through the main Minecraft instance, which only works client-side because servers don't have an individual player associated with them but clients do. To get around that, you could call the "/spawnpoint" from the player accessible from the event variable... nevermind, that only works with client-side players. Anyway, I found why the "player.setSpawnPoint" method was hard to find, the Forge mappings don't have a readable name for it yet. Currently, it's called "func_242111_a". I guess you'll just have to use that and switch it once it's got a more normal name, which should be obvious when it happens as it won't build and will complain about it not being able to find the method's name. Hope that helps!

**Comment by latedozer** [comment]
Hey, thanks for taking the time to look into this. But I had found the issue a while ago. (I'm setting spawn point via server entity)

I tried updating github but it didn't seem to work. I'll try update it again.

**Comment by latedozer** [comment]
Hopefully it's properly updated now. Again, thanks for the time you spent looking into it. From what I can tell, all I need to do know is make a player saved data file and a config file.
